---
- name: Configure and deploy e-commerce application
  hosts: web
  become: true
  vars_files:
    - group_vars/all.yml

  roles:
    - role: common
    - role: database
    - role: backend
    - role: frontend