---
- name: Pull backend Docker image
  docker_image:
    name: "Gibwanjau/brian-yolo-backend:v1.0.0"
    source: pull
    force_source: false
  register: pull_result
  until: pull_result is success
  retries: 3
  delay: 10
  become: yes

- name: Deploy Node.js Backend Container
  docker_container:
    name: "Gibwanjau-yolo-backend"
    image: "Gibwanjau/brian-yolo-backend:v1.0.0"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "app-net"
    ports:
      - "5000:5000"
    env:
      NODE_ENV: "production"
    command: "npm start"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  become: yes