name: Production Deployment

on:
  push:
    tags: ['v*.*.*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          docker build -f Dockerfile.prod -t gibwanjau/gibwanjau-yolo-client:v1.0.0:${{ github.ref_name }} ./client
          docker build -f Dockerfile.prod -t gibwanjau/gibwanjau-yolo-backend:v1.0.0:${{ github.ref_name }} ./backend
          docker push gibwanjau/gibwanjau-yolo-client:${{ github.ref_name }}
          docker push gibwanjau/gibwanjau-yolo-backend:${{ github.ref_name }}